##############################################################################################
# Terraform에서 정의하지 않는 Application 정의
# https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
##############################################################################################