
# Global Values
repoUrl: ''
targetRevision: HEAD
region: ''
account: ''
clusterName: ''
destinationServer: ''
argoNamespace: ''
argoProject: ''

##############################################################################################
# Terraform에서 정의하지 않는 Application 정의
# https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
##############################################################################################
Addons:
  # AWS ALB Controller
  aws-load-balancer-controller:
    enable: false
    name: aws-load-balancer-controller
    values:
      podDisruptionBudget:
        maxUnavailable: 1
      respectIgnoreDifferences: true
      ignoreDifferences:
      - group: ""
        kind: "Secret"
        jsonPointers:
        - /data
      - group: "admissionregistration.k8s.io"
        kind: "MutatingWebhookConfiguration"
        jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
      - group: "admissionregistration.k8s.io"
        kind: "ValidatingWebhookConfiguration"
        jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'    

  # RBAC
  K8sRbac:
    enable: false
    name: "k8s-rbac"
    sourceType: helm
    repoURL: ""
    targetRevision: ""
  ArgoRbac:
    enable: false
    name: "argo-rbac"
    sourceType: helm
    repoURL: ""
    targetRevision: ""

  # Argo Rollouts
  argo-rollouts:
    enable: false

  # Kyverno
  kyverno:
    enable: false    
  kyverno-policies:
    enable: false
    use_parent_chart: true
  kyverno-policy-reporter:
    enable: false
  
  # Metric Server
  metrics-server:
    enable: false

  # Reloader
  reloader:
    enable: false
