apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Values.name }}-repo-externalsecrets"
  namespace: "{{ .Values.namespace }}"
  labels:
    "argocd.argoproj.io/secret-type" : "repository"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: "{{ .Values.name }}-repo-secretstore"
  target:
    name: "{{ .Values.name }}-cfgstore-repo-secret"
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        type: "{{ .Values.type }}"
        insecure: "{{ .Values.insecure }}"
        url : "{{ .Values.repoUrl }}"
        username: "{{`{{ .username | toString }}`}}"
        password: "{{`{{ .password | toString }}`}}"
  data:
    - secretKey: "username"
      remoteRef: 
        key: {{ .Values.secretManagerName | quote }}
        property: {{ .Values.username }}      
    - secretKey: "password"
      remoteRef: 
        key: {{ .Values.secretManagerName | quote }}
        property: {{ .Values.password }}
