apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: "{{ .Values.name }}-repo-secretstore"
  namespace: "{{ .Values.namespace }}"
  labels:
    "argocd.argoproj.io/secret-type" : "repository"
spec:
  retrySettings:
    maxRetries: 5
    retryInterval: "10s"
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.region }}
      auth:
        jwt:
          serviceAccountRef: # ? IRSA federation enabled SeriveAccount
            name: {{ .Values.serviceAccountName }}